apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"nginx-app-pod","namespace":"default"},"spec":{"containers":[{"image":"nginx:1.18.0","name":"nginx-app-container","ports":[{"containerPort":80}]}]}}
    creationTimestamp: "2025-01-09T02:35:24Z"
    name: nginx-app-pod
    namespace: default
    resourceVersion: "19083"
    uid: b1e06c21-2625-4539-b2b9-167f401b46d1
  spec:
    containers:
    - image: nginx:1.18.0
      imagePullPolicy: IfNotPresent
      name: nginx-app-container
      ports:
      - containerPort: 80
        protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-sdjg5
        readOnly: true
    dnsPolicy: ClusterFirst
    enableServiceLinks: true
    nodeName: cwave-cluster-worker2
    preemptionPolicy: PreemptLowerPriority
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: kube-api-access-sdjg5
      projected:
        defaultMode: 420
        sources:
        - serviceAccountToken:
            expirationSeconds: 3607
            path: token
        - configMap:
            items:
            - key: ca.crt
              path: ca.crt
            name: kube-root-ca.crt
        - downwardAPI:
            items:
            - fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
              path: namespace
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2025-01-09T02:35:25Z"
      status: "True"
      type: PodReadyToStartContainers
    - lastProbeTime: null
      lastTransitionTime: "2025-01-09T02:35:24Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2025-01-09T02:35:25Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2025-01-09T02:35:25Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2025-01-09T02:35:24Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://249b9719221949943e80d21d307e6e6d0f81aa76816917c05c4751f1098a8cfc
      image: docker.io/library/nginx:1.18.0
      imageID: docker.io/library/nginx@sha256:e90ac5331fe095cea01b121a3627174b2e33e06e83720e9a934c7b8ccc9c55a0
      lastState: {}
      name: nginx-app-container
      ready: true
      restartCount: 0
      started: true
      state:
        running:
          startedAt: "2025-01-09T02:35:25Z"
    hostIP: 172.20.0.2
    hostIPs:
    - ip: 172.20.0.2
    phase: Running
    podIP: 10.110.2.4
    podIPs:
    - ip: 10.110.2.4
    qosClass: BestEffort
    startTime: "2025-01-09T02:35:24Z"
kind: List
metadata:
  resourceVersion: ""
