# docker-compose.yaml
# [연습] ubuntu 서버 실행하기
# 1. 
# version: "3.8"
# services:
#   ubuntu:
#     image: ubuntu:22.04
#     restart: no
# 2. tty : true
# version: '3.8'
# services:
#   ubuntu:
#     image: ubuntu:22.04
#     tty: true
#     stdin_open: true
#     restart: no
# 3. 
# version: '3.8'
# services:
#   ubuntu:
#     image: ubuntu:22.04
#     entrypoint: /bin/bash
#     command:
#       - -c
#       - sleep infinity
#     restart: no

# [연습] 환경변수를 이용하여 compose file 제어하기
# project-1.yaml
# version: '3.8'
# services:
#   ubuntu:
#     image: ubuntu:22.04
#     entrypoint: /bin/bash
#     command:
#       - -c
#       - echo 'env from "$FROM"'
#     restart: no
# 2.
# project-1.yaml
# version: '3.8'
# services:
#   ubuntu:
#     image: ubuntu:22.04
#     entrypoint: /bin/bash
#     command:
#       - -c
#       - echo 'env from "$FROM"' && echo 'env from ${BY:-default}'
#     restart: no

# [연습] command 에서 컨테이너 환경변수 사용하기
# version: '3.8'

# services:
#   ubuntu:
#     image: ubuntu:22.04
#     # environment:
#     #   - FROM="env definition"
#     #   - FROM="env2"
#     # env_file: .env
#     entrypoint: /bin/bash
#     command:
#       - -c
#       - echo 'env from ${FROM}' && echo env from $${FROM}
#     restart: no

# [연습] Docker compose에서 build 사용하기
# version: '3.8'
# services:
#   ubuntu:
#     container_name: server_build
#     build:
#       context: .
#       dockerfile_inline: |
#         FROM ubuntu:22.04
#         RUN apt-get update && apt-get upgrade && apt-get install -y curl
#     image: cloudwave/compose:inline_build.v1
#     restart: no
#   nginx:
#     image: nginx:latest
#     expose:
#       - 80
#     restart: always

version: '3.8'
name: 'volume-external'

services:
  master:
    image: ubuntu:22.04
    entrypoint: /bin/bash
    command:
      - -c
      - sleep infinity
    volumes:
      - vault:/root/vault

  slave:
    image: ubuntu:22.04
    entrypoint: /bin/bash
    command:
      - -c
      - sleep infinity
    volumes:
      - vault:/root/vault:ro

volumes:
    vault:
      external: true
      name: 'vault'