apiVersion: v1
kind: ReplicationController
metadata:
  name: goapp-rc
spec:
  replicas: 3
  selector:
    app: goapp-rc
  template:
    metadata:
      name: goapp-rc
      labels:
        app: goapp-rc
    spec:
      containers:
        - name: goapp-rc
          image: dangtong/goapp
          ports:
            - containerPort: 8080
